markdown: rdiscount

permalink: /:title/

url: http://cubernet.cn

name: Cubernet'Blog
author: Cubernet
description: "刘小垒的博客"

qq: 517324250
email: luxaole@gmail.com

disqus: cubernet
weibo: luxaole
github: Cubernet

pygments: true

paginate: 15

about: "程序猿一只，深陷读博大坑不能自拔。\n热爱编程，开源爱好者，喜欢linux，github等。\n喜欢干净整洁的代码，轻微代码洁癖。"

funnypicsurl: [/assets/funnypics/编程时间分配图.png,
            /assets/funnypics/程序员的一生.jpg,
            /assets/funnypics/程序员的早期教育.gif,
            /assets/funnypics/程序员的职业生涯.jpg,
            /assets/funnypics/程序员那些事.jpg,
            /assets/funnypics/程序员生存现状.jpg,
            /assets/funnypics/程序员在囧途.jpg,
            /assets/funnypics/程序员自我诊断书.jpg,
            /assets/funnypics/程序猿崛起.jpg,
            /assets/funnypics/机智的老太太.jpg,
            /assets/funnypics/让你当程序员.jpg,
            /assets/funnypics/我有女朋友.jpg,
            /assets/funnypics/学习和工作的区别.jpg,
            /assets/funnypics/再加班就跳楼.jpg,
            /assets/funnypics/真实的问题.jpg,
            /assets/funnypics/最杯具的职业莫过程序员.jpg
            ]

funnypicstitle: [编程时间分配图,
                 程序员的一生,
                 程序员的早期教育,
                 程序员的职业生涯,
                 程序员那些事,
                 程序员生存现状,
                 程序员在囧途,
                 程序员自我诊断书,
                 程序猿崛起,
                 机智的老太太,
                 让你当程序员,
                 我有女朋友,
                 学习和工作的区别,
                 再加班就跳楼,
                 真实的问题,
                 最杯具的职业莫过程序员]